// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.17.3
// source: api/ova-reason-api.proto

package ova_reason_api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateReasonRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId   uint64 `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	ActionId uint64 `protobuf:"varint,2,opt,name=actionId,proto3" json:"actionId,omitempty"`
	Why      string `protobuf:"bytes,3,opt,name=why,proto3" json:"why,omitempty"`
}

func (x *CreateReasonRequest) Reset() {
	*x = CreateReasonRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_ova_reason_api_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateReasonRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateReasonRequest) ProtoMessage() {}

func (x *CreateReasonRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_ova_reason_api_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateReasonRequest.ProtoReflect.Descriptor instead.
func (*CreateReasonRequest) Descriptor() ([]byte, []int) {
	return file_api_ova_reason_api_proto_rawDescGZIP(), []int{0}
}

func (x *CreateReasonRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *CreateReasonRequest) GetActionId() uint64 {
	if x != nil {
		return x.ActionId
	}
	return 0
}

func (x *CreateReasonRequest) GetWhy() string {
	if x != nil {
		return x.Why
	}
	return ""
}

type CreateReasonResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *CreateReasonResponse) Reset() {
	*x = CreateReasonResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_ova_reason_api_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateReasonResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateReasonResponse) ProtoMessage() {}

func (x *CreateReasonResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_ova_reason_api_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateReasonResponse.ProtoReflect.Descriptor instead.
func (*CreateReasonResponse) Descriptor() ([]byte, []int) {
	return file_api_ova_reason_api_proto_rawDescGZIP(), []int{1}
}

func (x *CreateReasonResponse) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type DescribeReasonRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *DescribeReasonRequest) Reset() {
	*x = DescribeReasonRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_ova_reason_api_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DescribeReasonRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DescribeReasonRequest) ProtoMessage() {}

func (x *DescribeReasonRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_ova_reason_api_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DescribeReasonRequest.ProtoReflect.Descriptor instead.
func (*DescribeReasonRequest) Descriptor() ([]byte, []int) {
	return file_api_ova_reason_api_proto_rawDescGZIP(), []int{2}
}

func (x *DescribeReasonRequest) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type DescribeReasonResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Reason *Reason `protobuf:"bytes,1,opt,name=Reason,proto3" json:"Reason,omitempty"`
}

func (x *DescribeReasonResponse) Reset() {
	*x = DescribeReasonResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_ova_reason_api_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DescribeReasonResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DescribeReasonResponse) ProtoMessage() {}

func (x *DescribeReasonResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_ova_reason_api_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DescribeReasonResponse.ProtoReflect.Descriptor instead.
func (*DescribeReasonResponse) Descriptor() ([]byte, []int) {
	return file_api_ova_reason_api_proto_rawDescGZIP(), []int{3}
}

func (x *DescribeReasonResponse) GetReason() *Reason {
	if x != nil {
		return x.Reason
	}
	return nil
}

type RemoveReasonRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *RemoveReasonRequest) Reset() {
	*x = RemoveReasonRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_ova_reason_api_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RemoveReasonRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveReasonRequest) ProtoMessage() {}

func (x *RemoveReasonRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_ova_reason_api_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveReasonRequest.ProtoReflect.Descriptor instead.
func (*RemoveReasonRequest) Descriptor() ([]byte, []int) {
	return file_api_ova_reason_api_proto_rawDescGZIP(), []int{4}
}

func (x *RemoveReasonRequest) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type ListReasonsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Items []*Reason `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
}

func (x *ListReasonsResponse) Reset() {
	*x = ListReasonsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_ova_reason_api_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListReasonsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListReasonsResponse) ProtoMessage() {}

func (x *ListReasonsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_ova_reason_api_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListReasonsResponse.ProtoReflect.Descriptor instead.
func (*ListReasonsResponse) Descriptor() ([]byte, []int) {
	return file_api_ova_reason_api_proto_rawDescGZIP(), []int{5}
}

func (x *ListReasonsResponse) GetItems() []*Reason {
	if x != nil {
		return x.Items
	}
	return nil
}

type Reason struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id       uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId   uint64 `protobuf:"varint,2,opt,name=userId,proto3" json:"userId,omitempty"`
	ActionId uint64 `protobuf:"varint,3,opt,name=actionId,proto3" json:"actionId,omitempty"`
	Why      string `protobuf:"bytes,4,opt,name=why,proto3" json:"why,omitempty"`
}

func (x *Reason) Reset() {
	*x = Reason{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_ova_reason_api_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Reason) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Reason) ProtoMessage() {}

func (x *Reason) ProtoReflect() protoreflect.Message {
	mi := &file_api_ova_reason_api_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Reason.ProtoReflect.Descriptor instead.
func (*Reason) Descriptor() ([]byte, []int) {
	return file_api_ova_reason_api_proto_rawDescGZIP(), []int{6}
}

func (x *Reason) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Reason) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *Reason) GetActionId() uint64 {
	if x != nil {
		return x.ActionId
	}
	return 0
}

func (x *Reason) GetWhy() string {
	if x != nil {
		return x.Why
	}
	return ""
}

var File_api_ova_reason_api_proto protoreflect.FileDescriptor

var file_api_ova_reason_api_proto_rawDesc = []byte{
	0x0a, 0x18, 0x61, 0x70, 0x69, 0x2f, 0x6f, 0x76, 0x61, 0x2d, 0x72, 0x65, 0x61, 0x73, 0x6f, 0x6e,
	0x2d, 0x61, 0x70, 0x69, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0e, 0x6f, 0x76, 0x61, 0x2e,
	0x72, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x2e, 0x61, 0x70, 0x69, 0x1a, 0x1b, 0x67, 0x6f, 0x6f, 0x67,
	0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x65, 0x6d, 0x70, 0x74,
	0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x5b, 0x0a, 0x13, 0x43, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x52, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16,
	0x0a, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06,
	0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e,
	0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x08, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e,
	0x49, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x77, 0x68, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x03, 0x77, 0x68, 0x79, 0x22, 0x26, 0x0a, 0x14, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65,
	0x61, 0x73, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x0e, 0x0a, 0x02,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x02, 0x69, 0x64, 0x22, 0x27, 0x0a, 0x15,
	0x44, 0x65, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x52, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x04, 0x52, 0x02, 0x69, 0x64, 0x22, 0x48, 0x0a, 0x16, 0x44, 0x65, 0x73, 0x63, 0x72, 0x69, 0x62,
	0x65, 0x52, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x2e, 0x0a, 0x06, 0x52, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x16, 0x2e, 0x6f, 0x76, 0x61, 0x2e, 0x72, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x2e, 0x61, 0x70, 0x69,
	0x2e, 0x52, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x52, 0x06, 0x52, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x22,
	0x25, 0x0a, 0x13, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x52, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x04, 0x52, 0x02, 0x69, 0x64, 0x22, 0x43, 0x0a, 0x13, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65,
	0x61, 0x73, 0x6f, 0x6e, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2c, 0x0a,
	0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x6f,
	0x76, 0x61, 0x2e, 0x72, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x52, 0x65,
	0x61, 0x73, 0x6f, 0x6e, 0x52, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x22, 0x5e, 0x0a, 0x06, 0x52,
	0x65, 0x61, 0x73, 0x6f, 0x6e, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x04, 0x52, 0x02, 0x69, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x1a, 0x0a,
	0x08, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x04, 0x52,
	0x08, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x77, 0x68, 0x79,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x77, 0x68, 0x79, 0x32, 0xe0, 0x02, 0x0a, 0x09,
	0x52, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x52, 0x70, 0x63, 0x12, 0x59, 0x0a, 0x0c, 0x43, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x52, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x12, 0x23, 0x2e, 0x6f, 0x76, 0x61, 0x2e,
	0x72, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x52, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x24,
	0x2e, 0x6f, 0x76, 0x61, 0x2e, 0x72, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x2e, 0x61, 0x70, 0x69, 0x2e,
	0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x5f, 0x0a, 0x0e, 0x44, 0x65, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65,
	0x52, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x12, 0x25, 0x2e, 0x6f, 0x76, 0x61, 0x2e, 0x72, 0x65, 0x61,
	0x73, 0x6f, 0x6e, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x44, 0x65, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65,
	0x52, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x26, 0x2e,
	0x6f, 0x76, 0x61, 0x2e, 0x72, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x44,
	0x65, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x52, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x4a, 0x0a, 0x0b, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x61,
	0x73, 0x6f, 0x6e, 0x73, 0x12, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a, 0x23, 0x2e, 0x6f,
	0x76, 0x61, 0x2e, 0x72, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x4c, 0x69,
	0x73, 0x74, 0x52, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x4b, 0x0a, 0x0c, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x52, 0x65, 0x61, 0x73, 0x6f,
	0x6e, 0x12, 0x23, 0x2e, 0x6f, 0x76, 0x61, 0x2e, 0x72, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x2e, 0x61,
	0x70, 0x69, 0x2e, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x52, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x42, 0x44,
	0x5a, 0x42, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6f, 0x7a, 0x6f,
	0x6e, 0x76, 0x61, 0x2f, 0x6f, 0x76, 0x61, 0x2d, 0x72, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x2d, 0x61,
	0x70, 0x69, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x6f, 0x76, 0x61, 0x2d, 0x72, 0x65, 0x61, 0x73, 0x6f,
	0x6e, 0x2d, 0x61, 0x70, 0x69, 0x3b, 0x6f, 0x76, 0x61, 0x5f, 0x72, 0x65, 0x61, 0x73, 0x6f, 0x6e,
	0x5f, 0x61, 0x70, 0x69, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_ova_reason_api_proto_rawDescOnce sync.Once
	file_api_ova_reason_api_proto_rawDescData = file_api_ova_reason_api_proto_rawDesc
)

func file_api_ova_reason_api_proto_rawDescGZIP() []byte {
	file_api_ova_reason_api_proto_rawDescOnce.Do(func() {
		file_api_ova_reason_api_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_ova_reason_api_proto_rawDescData)
	})
	return file_api_ova_reason_api_proto_rawDescData
}

var file_api_ova_reason_api_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_api_ova_reason_api_proto_goTypes = []interface{}{
	(*CreateReasonRequest)(nil),    // 0: ova.reason.api.CreateReasonRequest
	(*CreateReasonResponse)(nil),   // 1: ova.reason.api.CreateReasonResponse
	(*DescribeReasonRequest)(nil),  // 2: ova.reason.api.DescribeReasonRequest
	(*DescribeReasonResponse)(nil), // 3: ova.reason.api.DescribeReasonResponse
	(*RemoveReasonRequest)(nil),    // 4: ova.reason.api.RemoveReasonRequest
	(*ListReasonsResponse)(nil),    // 5: ova.reason.api.ListReasonsResponse
	(*Reason)(nil),                 // 6: ova.reason.api.Reason
	(*emptypb.Empty)(nil),          // 7: google.protobuf.Empty
}
var file_api_ova_reason_api_proto_depIdxs = []int32{
	6, // 0: ova.reason.api.DescribeReasonResponse.Reason:type_name -> ova.reason.api.Reason
	6, // 1: ova.reason.api.ListReasonsResponse.items:type_name -> ova.reason.api.Reason
	0, // 2: ova.reason.api.ReasonRpc.CreateReason:input_type -> ova.reason.api.CreateReasonRequest
	2, // 3: ova.reason.api.ReasonRpc.DescribeReason:input_type -> ova.reason.api.DescribeReasonRequest
	7, // 4: ova.reason.api.ReasonRpc.ListReasons:input_type -> google.protobuf.Empty
	4, // 5: ova.reason.api.ReasonRpc.RemoveReason:input_type -> ova.reason.api.RemoveReasonRequest
	1, // 6: ova.reason.api.ReasonRpc.CreateReason:output_type -> ova.reason.api.CreateReasonResponse
	3, // 7: ova.reason.api.ReasonRpc.DescribeReason:output_type -> ova.reason.api.DescribeReasonResponse
	5, // 8: ova.reason.api.ReasonRpc.ListReasons:output_type -> ova.reason.api.ListReasonsResponse
	7, // 9: ova.reason.api.ReasonRpc.RemoveReason:output_type -> google.protobuf.Empty
	6, // [6:10] is the sub-list for method output_type
	2, // [2:6] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_api_ova_reason_api_proto_init() }
func file_api_ova_reason_api_proto_init() {
	if File_api_ova_reason_api_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_ova_reason_api_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateReasonRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_ova_reason_api_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateReasonResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_ova_reason_api_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DescribeReasonRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_ova_reason_api_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DescribeReasonResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_ova_reason_api_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RemoveReasonRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_ova_reason_api_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListReasonsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_ova_reason_api_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Reason); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_ova_reason_api_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_ova_reason_api_proto_goTypes,
		DependencyIndexes: file_api_ova_reason_api_proto_depIdxs,
		MessageInfos:      file_api_ova_reason_api_proto_msgTypes,
	}.Build()
	File_api_ova_reason_api_proto = out.File
	file_api_ova_reason_api_proto_rawDesc = nil
	file_api_ova_reason_api_proto_goTypes = nil
	file_api_ova_reason_api_proto_depIdxs = nil
}
