// Code generated by protoc-gen-go. DO NOT EDIT.
// source: ova-reason-api.proto

package ova_reason_api

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/golang/protobuf/ptypes/empty"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type BulkCreateReasonRequest struct {
	Reasons              []*CreateReasonRequest `protobuf:"bytes,1,rep,name=reasons,proto3" json:"reasons,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *BulkCreateReasonRequest) Reset()         { *m = BulkCreateReasonRequest{} }
func (m *BulkCreateReasonRequest) String() string { return proto.CompactTextString(m) }
func (*BulkCreateReasonRequest) ProtoMessage()    {}
func (*BulkCreateReasonRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1e1c3f3c6e5e68fd, []int{0}
}

func (m *BulkCreateReasonRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BulkCreateReasonRequest.Unmarshal(m, b)
}
func (m *BulkCreateReasonRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BulkCreateReasonRequest.Marshal(b, m, deterministic)
}
func (m *BulkCreateReasonRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BulkCreateReasonRequest.Merge(m, src)
}
func (m *BulkCreateReasonRequest) XXX_Size() int {
	return xxx_messageInfo_BulkCreateReasonRequest.Size(m)
}
func (m *BulkCreateReasonRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_BulkCreateReasonRequest.DiscardUnknown(m)
}

var xxx_messageInfo_BulkCreateReasonRequest proto.InternalMessageInfo

func (m *BulkCreateReasonRequest) GetReasons() []*CreateReasonRequest {
	if m != nil {
		return m.Reasons
	}
	return nil
}

type BulkCreateReasonResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BulkCreateReasonResponse) Reset()         { *m = BulkCreateReasonResponse{} }
func (m *BulkCreateReasonResponse) String() string { return proto.CompactTextString(m) }
func (*BulkCreateReasonResponse) ProtoMessage()    {}
func (*BulkCreateReasonResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1e1c3f3c6e5e68fd, []int{1}
}

func (m *BulkCreateReasonResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BulkCreateReasonResponse.Unmarshal(m, b)
}
func (m *BulkCreateReasonResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BulkCreateReasonResponse.Marshal(b, m, deterministic)
}
func (m *BulkCreateReasonResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BulkCreateReasonResponse.Merge(m, src)
}
func (m *BulkCreateReasonResponse) XXX_Size() int {
	return xxx_messageInfo_BulkCreateReasonResponse.Size(m)
}
func (m *BulkCreateReasonResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_BulkCreateReasonResponse.DiscardUnknown(m)
}

var xxx_messageInfo_BulkCreateReasonResponse proto.InternalMessageInfo

type CreateReasonRequest struct {
	UserId               uint64   `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	ActionId             uint64   `protobuf:"varint,2,opt,name=actionId,proto3" json:"actionId,omitempty"`
	Why                  string   `protobuf:"bytes,3,opt,name=why,proto3" json:"why,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateReasonRequest) Reset()         { *m = CreateReasonRequest{} }
func (m *CreateReasonRequest) String() string { return proto.CompactTextString(m) }
func (*CreateReasonRequest) ProtoMessage()    {}
func (*CreateReasonRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1e1c3f3c6e5e68fd, []int{2}
}

func (m *CreateReasonRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateReasonRequest.Unmarshal(m, b)
}
func (m *CreateReasonRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateReasonRequest.Marshal(b, m, deterministic)
}
func (m *CreateReasonRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateReasonRequest.Merge(m, src)
}
func (m *CreateReasonRequest) XXX_Size() int {
	return xxx_messageInfo_CreateReasonRequest.Size(m)
}
func (m *CreateReasonRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateReasonRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateReasonRequest proto.InternalMessageInfo

func (m *CreateReasonRequest) GetUserId() uint64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *CreateReasonRequest) GetActionId() uint64 {
	if m != nil {
		return m.ActionId
	}
	return 0
}

func (m *CreateReasonRequest) GetWhy() string {
	if m != nil {
		return m.Why
	}
	return ""
}

type CreateReasonResponse struct {
	Id                   uint64   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateReasonResponse) Reset()         { *m = CreateReasonResponse{} }
func (m *CreateReasonResponse) String() string { return proto.CompactTextString(m) }
func (*CreateReasonResponse) ProtoMessage()    {}
func (*CreateReasonResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1e1c3f3c6e5e68fd, []int{3}
}

func (m *CreateReasonResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateReasonResponse.Unmarshal(m, b)
}
func (m *CreateReasonResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateReasonResponse.Marshal(b, m, deterministic)
}
func (m *CreateReasonResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateReasonResponse.Merge(m, src)
}
func (m *CreateReasonResponse) XXX_Size() int {
	return xxx_messageInfo_CreateReasonResponse.Size(m)
}
func (m *CreateReasonResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateReasonResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateReasonResponse proto.InternalMessageInfo

func (m *CreateReasonResponse) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type ReplaceReasonRequest struct {
	Id                   uint64   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId               uint64   `protobuf:"varint,2,opt,name=userId,proto3" json:"userId,omitempty"`
	ActionId             uint64   `protobuf:"varint,3,opt,name=actionId,proto3" json:"actionId,omitempty"`
	Why                  string   `protobuf:"bytes,4,opt,name=why,proto3" json:"why,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReplaceReasonRequest) Reset()         { *m = ReplaceReasonRequest{} }
func (m *ReplaceReasonRequest) String() string { return proto.CompactTextString(m) }
func (*ReplaceReasonRequest) ProtoMessage()    {}
func (*ReplaceReasonRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1e1c3f3c6e5e68fd, []int{4}
}

func (m *ReplaceReasonRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReplaceReasonRequest.Unmarshal(m, b)
}
func (m *ReplaceReasonRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReplaceReasonRequest.Marshal(b, m, deterministic)
}
func (m *ReplaceReasonRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReplaceReasonRequest.Merge(m, src)
}
func (m *ReplaceReasonRequest) XXX_Size() int {
	return xxx_messageInfo_ReplaceReasonRequest.Size(m)
}
func (m *ReplaceReasonRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ReplaceReasonRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ReplaceReasonRequest proto.InternalMessageInfo

func (m *ReplaceReasonRequest) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *ReplaceReasonRequest) GetUserId() uint64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *ReplaceReasonRequest) GetActionId() uint64 {
	if m != nil {
		return m.ActionId
	}
	return 0
}

func (m *ReplaceReasonRequest) GetWhy() string {
	if m != nil {
		return m.Why
	}
	return ""
}

type ReplaceReasonResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReplaceReasonResponse) Reset()         { *m = ReplaceReasonResponse{} }
func (m *ReplaceReasonResponse) String() string { return proto.CompactTextString(m) }
func (*ReplaceReasonResponse) ProtoMessage()    {}
func (*ReplaceReasonResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1e1c3f3c6e5e68fd, []int{5}
}

func (m *ReplaceReasonResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReplaceReasonResponse.Unmarshal(m, b)
}
func (m *ReplaceReasonResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReplaceReasonResponse.Marshal(b, m, deterministic)
}
func (m *ReplaceReasonResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReplaceReasonResponse.Merge(m, src)
}
func (m *ReplaceReasonResponse) XXX_Size() int {
	return xxx_messageInfo_ReplaceReasonResponse.Size(m)
}
func (m *ReplaceReasonResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ReplaceReasonResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ReplaceReasonResponse proto.InternalMessageInfo

type DescribeReasonRequest struct {
	Id                   uint64   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DescribeReasonRequest) Reset()         { *m = DescribeReasonRequest{} }
func (m *DescribeReasonRequest) String() string { return proto.CompactTextString(m) }
func (*DescribeReasonRequest) ProtoMessage()    {}
func (*DescribeReasonRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1e1c3f3c6e5e68fd, []int{6}
}

func (m *DescribeReasonRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DescribeReasonRequest.Unmarshal(m, b)
}
func (m *DescribeReasonRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DescribeReasonRequest.Marshal(b, m, deterministic)
}
func (m *DescribeReasonRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DescribeReasonRequest.Merge(m, src)
}
func (m *DescribeReasonRequest) XXX_Size() int {
	return xxx_messageInfo_DescribeReasonRequest.Size(m)
}
func (m *DescribeReasonRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DescribeReasonRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DescribeReasonRequest proto.InternalMessageInfo

func (m *DescribeReasonRequest) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type DescribeReasonResponse struct {
	Reason               *Reason  `protobuf:"bytes,1,opt,name=Reason,proto3" json:"Reason,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DescribeReasonResponse) Reset()         { *m = DescribeReasonResponse{} }
func (m *DescribeReasonResponse) String() string { return proto.CompactTextString(m) }
func (*DescribeReasonResponse) ProtoMessage()    {}
func (*DescribeReasonResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1e1c3f3c6e5e68fd, []int{7}
}

func (m *DescribeReasonResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DescribeReasonResponse.Unmarshal(m, b)
}
func (m *DescribeReasonResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DescribeReasonResponse.Marshal(b, m, deterministic)
}
func (m *DescribeReasonResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DescribeReasonResponse.Merge(m, src)
}
func (m *DescribeReasonResponse) XXX_Size() int {
	return xxx_messageInfo_DescribeReasonResponse.Size(m)
}
func (m *DescribeReasonResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DescribeReasonResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DescribeReasonResponse proto.InternalMessageInfo

func (m *DescribeReasonResponse) GetReason() *Reason {
	if m != nil {
		return m.Reason
	}
	return nil
}

type RemoveReasonRequest struct {
	Id                   uint64   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RemoveReasonRequest) Reset()         { *m = RemoveReasonRequest{} }
func (m *RemoveReasonRequest) String() string { return proto.CompactTextString(m) }
func (*RemoveReasonRequest) ProtoMessage()    {}
func (*RemoveReasonRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1e1c3f3c6e5e68fd, []int{8}
}

func (m *RemoveReasonRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RemoveReasonRequest.Unmarshal(m, b)
}
func (m *RemoveReasonRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RemoveReasonRequest.Marshal(b, m, deterministic)
}
func (m *RemoveReasonRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RemoveReasonRequest.Merge(m, src)
}
func (m *RemoveReasonRequest) XXX_Size() int {
	return xxx_messageInfo_RemoveReasonRequest.Size(m)
}
func (m *RemoveReasonRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RemoveReasonRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RemoveReasonRequest proto.InternalMessageInfo

func (m *RemoveReasonRequest) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type RemoveReasonResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RemoveReasonResponse) Reset()         { *m = RemoveReasonResponse{} }
func (m *RemoveReasonResponse) String() string { return proto.CompactTextString(m) }
func (*RemoveReasonResponse) ProtoMessage()    {}
func (*RemoveReasonResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1e1c3f3c6e5e68fd, []int{9}
}

func (m *RemoveReasonResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RemoveReasonResponse.Unmarshal(m, b)
}
func (m *RemoveReasonResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RemoveReasonResponse.Marshal(b, m, deterministic)
}
func (m *RemoveReasonResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RemoveReasonResponse.Merge(m, src)
}
func (m *RemoveReasonResponse) XXX_Size() int {
	return xxx_messageInfo_RemoveReasonResponse.Size(m)
}
func (m *RemoveReasonResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RemoveReasonResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RemoveReasonResponse proto.InternalMessageInfo

type ListReasonsResponse struct {
	Items                []*Reason `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *ListReasonsResponse) Reset()         { *m = ListReasonsResponse{} }
func (m *ListReasonsResponse) String() string { return proto.CompactTextString(m) }
func (*ListReasonsResponse) ProtoMessage()    {}
func (*ListReasonsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1e1c3f3c6e5e68fd, []int{10}
}

func (m *ListReasonsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListReasonsResponse.Unmarshal(m, b)
}
func (m *ListReasonsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListReasonsResponse.Marshal(b, m, deterministic)
}
func (m *ListReasonsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListReasonsResponse.Merge(m, src)
}
func (m *ListReasonsResponse) XXX_Size() int {
	return xxx_messageInfo_ListReasonsResponse.Size(m)
}
func (m *ListReasonsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListReasonsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListReasonsResponse proto.InternalMessageInfo

func (m *ListReasonsResponse) GetItems() []*Reason {
	if m != nil {
		return m.Items
	}
	return nil
}

type Reason struct {
	Id                   uint64   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId               uint64   `protobuf:"varint,2,opt,name=userId,proto3" json:"userId,omitempty"`
	ActionId             uint64   `protobuf:"varint,3,opt,name=actionId,proto3" json:"actionId,omitempty"`
	Why                  string   `protobuf:"bytes,4,opt,name=why,proto3" json:"why,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Reason) Reset()         { *m = Reason{} }
func (m *Reason) String() string { return proto.CompactTextString(m) }
func (*Reason) ProtoMessage()    {}
func (*Reason) Descriptor() ([]byte, []int) {
	return fileDescriptor_1e1c3f3c6e5e68fd, []int{11}
}

func (m *Reason) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Reason.Unmarshal(m, b)
}
func (m *Reason) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Reason.Marshal(b, m, deterministic)
}
func (m *Reason) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Reason.Merge(m, src)
}
func (m *Reason) XXX_Size() int {
	return xxx_messageInfo_Reason.Size(m)
}
func (m *Reason) XXX_DiscardUnknown() {
	xxx_messageInfo_Reason.DiscardUnknown(m)
}

var xxx_messageInfo_Reason proto.InternalMessageInfo

func (m *Reason) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Reason) GetUserId() uint64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *Reason) GetActionId() uint64 {
	if m != nil {
		return m.ActionId
	}
	return 0
}

func (m *Reason) GetWhy() string {
	if m != nil {
		return m.Why
	}
	return ""
}

func init() {
	proto.RegisterType((*BulkCreateReasonRequest)(nil), "ova.reason.api.BulkCreateReasonRequest")
	proto.RegisterType((*BulkCreateReasonResponse)(nil), "ova.reason.api.BulkCreateReasonResponse")
	proto.RegisterType((*CreateReasonRequest)(nil), "ova.reason.api.CreateReasonRequest")
	proto.RegisterType((*CreateReasonResponse)(nil), "ova.reason.api.CreateReasonResponse")
	proto.RegisterType((*ReplaceReasonRequest)(nil), "ova.reason.api.ReplaceReasonRequest")
	proto.RegisterType((*ReplaceReasonResponse)(nil), "ova.reason.api.ReplaceReasonResponse")
	proto.RegisterType((*DescribeReasonRequest)(nil), "ova.reason.api.DescribeReasonRequest")
	proto.RegisterType((*DescribeReasonResponse)(nil), "ova.reason.api.DescribeReasonResponse")
	proto.RegisterType((*RemoveReasonRequest)(nil), "ova.reason.api.RemoveReasonRequest")
	proto.RegisterType((*RemoveReasonResponse)(nil), "ova.reason.api.RemoveReasonResponse")
	proto.RegisterType((*ListReasonsResponse)(nil), "ova.reason.api.ListReasonsResponse")
	proto.RegisterType((*Reason)(nil), "ova.reason.api.Reason")
}

func init() { proto.RegisterFile("ova-reason-api.proto", fileDescriptor_1e1c3f3c6e5e68fd) }

var fileDescriptor_1e1c3f3c6e5e68fd = []byte{
	// 564 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x95, 0xdf, 0x6e, 0xd3, 0x30,
	0x14, 0xc6, 0x95, 0x76, 0x2b, 0xdb, 0xe9, 0x5a, 0x86, 0xfb, 0x67, 0x91, 0xe1, 0xa2, 0x32, 0xdd,
	0x56, 0x4d, 0x2c, 0x91, 0xca, 0x1d, 0x88, 0x9b, 0x6e, 0x48, 0x4c, 0xe2, 0x2a, 0x57, 0x08, 0x10,
	0x93, 0xdb, 0x9a, 0xce, 0x6a, 0x1b, 0x9b, 0x3a, 0x09, 0x1a, 0x08, 0x09, 0xf1, 0x0a, 0xbc, 0x0f,
	0x2f, 0xc1, 0x2b, 0xf0, 0x20, 0xa8, 0x89, 0xd3, 0xe5, 0x5f, 0x5b, 0x6e, 0xb8, 0xab, 0xed, 0x2f,
	0xe7, 0xf7, 0x1d, 0xfb, 0xb3, 0x0b, 0x4d, 0x11, 0xd0, 0xf3, 0x05, 0xa3, 0x4a, 0xb8, 0xe7, 0x54,
	0x72, 0x4b, 0x2e, 0x84, 0x27, 0x50, 0x5d, 0x04, 0xd4, 0x8a, 0x66, 0x2d, 0x2a, 0x39, 0x7e, 0x34,
	0x11, 0x62, 0x32, 0x63, 0x36, 0x95, 0xdc, 0xa6, 0xae, 0x2b, 0x3c, 0xea, 0x71, 0xe1, 0xaa, 0x48,
	0x8d, 0x1f, 0xea, 0xd5, 0x70, 0x34, 0xf4, 0x3f, 0xda, 0x6c, 0x2e, 0xbd, 0xdb, 0x68, 0x91, 0xbc,
	0x81, 0xa3, 0x81, 0x3f, 0x9b, 0x5e, 0x2c, 0x18, 0xf5, 0x98, 0x13, 0x96, 0x74, 0xd8, 0x27, 0x9f,
	0x29, 0x0f, 0xbd, 0x80, 0x7b, 0x11, 0x43, 0x99, 0x46, 0xa7, 0xdc, 0xab, 0xf6, 0x1f, 0x5b, 0x69,
	0xae, 0x55, 0xf0, 0x95, 0x13, 0x7f, 0x43, 0x30, 0x98, 0xf9, 0xca, 0x4a, 0x0a, 0x57, 0x31, 0xf2,
	0x0e, 0x1a, 0x45, 0xc4, 0x36, 0x54, 0x7c, 0xc5, 0x16, 0x57, 0x63, 0xd3, 0xe8, 0x18, 0xbd, 0x1d,
	0x47, 0x8f, 0x10, 0x86, 0x3d, 0x3a, 0x5a, 0xb6, 0x74, 0x35, 0x36, 0x4b, 0xe1, 0xca, 0x6a, 0x8c,
	0x0e, 0xa1, 0xfc, 0xf9, 0xe6, 0xd6, 0x2c, 0x77, 0x8c, 0xde, 0xbe, 0xb3, 0xfc, 0x49, 0x4e, 0xa0,
	0x59, 0x04, 0x45, 0x75, 0x28, 0xf1, 0xb8, 0x72, 0x89, 0x8f, 0xc9, 0x0c, 0x9a, 0x0e, 0x93, 0x33,
	0x3a, 0xca, 0xb8, 0xc8, 0xe8, 0x12, 0xae, 0x4a, 0x6b, 0x5d, 0x95, 0x8b, 0x5d, 0xed, 0xdc, 0xb9,
	0x3a, 0x82, 0x56, 0x86, 0xa6, 0xf7, 0xe2, 0x14, 0x5a, 0x97, 0x4c, 0x8d, 0x16, 0x7c, 0xb8, 0xd9,
	0x07, 0x79, 0x05, 0xed, 0xac, 0x50, 0x77, 0x66, 0x41, 0x25, 0x9a, 0x09, 0xd5, 0xd5, 0x7e, 0x3b,
	0x7b, 0x50, 0x5a, 0xaf, 0x55, 0xe4, 0x18, 0x1a, 0x0e, 0x9b, 0x8b, 0x60, 0x0b, 0xb0, 0xbd, 0xdc,
	0xa0, 0xa4, 0x4c, 0x3b, 0xbe, 0x80, 0xc6, 0x6b, 0xae, 0xbc, 0x68, 0x56, 0xad, 0x5c, 0x3c, 0x81,
	0x5d, 0xee, 0xb1, 0x79, 0x9c, 0x96, 0x75, 0x26, 0x22, 0x11, 0xf9, 0x10, 0x7b, 0xfe, 0x3f, 0xfb,
	0xdd, 0xff, 0xb5, 0x0b, 0xfb, 0x9a, 0x28, 0x47, 0xc8, 0x85, 0x83, 0x64, 0x26, 0xd0, 0xbf, 0x44,
	0x19, 0x77, 0x37, 0x8b, 0xf4, 0x6e, 0x34, 0x7e, 0xfc, 0xfe, 0xf3, 0xb3, 0x54, 0x23, 0x7b, 0xb6,
	0x4e, 0xfe, 0x33, 0xe3, 0x0c, 0x7d, 0x37, 0xe0, 0x41, 0x36, 0xfd, 0x0a, 0x9d, 0x66, 0x0b, 0xae,
	0xb9, 0x7a, 0xb8, 0xb7, 0x5d, 0xa8, 0xe9, 0x66, 0x48, 0x47, 0xa4, 0x16, 0xd3, 0xed, 0xa1, 0x3f,
	0x9b, 0x2e, 0x2d, 0x04, 0x50, 0x4b, 0x05, 0x0e, 0x75, 0xf3, 0x07, 0x92, 0x4f, 0x3f, 0x3e, 0xde,
	0xa2, 0x4a, 0x73, 0xf1, 0x1d, 0xf7, 0x2b, 0x1f, 0x7f, 0x8b, 0xb8, 0xf5, 0x74, 0x4c, 0x51, 0xae,
	0x64, 0x61, 0xde, 0xf1, 0xc9, 0x36, 0x99, 0x46, 0xb7, 0x42, 0xf4, 0x7d, 0x94, 0x46, 0xa3, 0xf7,
	0x50, 0x4d, 0xa4, 0x12, 0xb5, 0xad, 0xe8, 0xd9, 0xb3, 0xe2, 0x67, 0xcf, 0x7a, 0xb9, 0x7c, 0xf6,
	0x70, 0xee, 0xe4, 0x0b, 0xa2, 0x4c, 0x0e, 0x43, 0x04, 0xa0, 0xd5, 0x99, 0x22, 0x09, 0x07, 0xc9,
	0xbb, 0x90, 0x0f, 0x50, 0xc1, 0x85, 0xc2, 0xdd, 0xcd, 0xa2, 0x74, 0x3f, 0x67, 0xe9, 0x7e, 0x06,
	0x97, 0x6f, 0x07, 0x13, 0xee, 0xdd, 0xf8, 0x43, 0x6b, 0x24, 0xe6, 0xb6, 0xf8, 0x22, 0xdc, 0x80,
	0xda, 0xe9, 0xbf, 0x03, 0x5b, 0x4e, 0x27, 0x99, 0xa9, 0xe7, 0x22, 0xa0, 0xd7, 0xd1, 0xf0, 0x9a,
	0x4a, 0x3e, 0xac, 0x84, 0xed, 0x3f, 0xfd, 0x1b, 0x00, 0x00, 0xff, 0xff, 0x23, 0x79, 0x5c, 0x84,
	0x49, 0x06, 0x00, 0x00,
}
