// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api/ova-reason-api.proto

package ova_reason_api

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/golang/protobuf/ptypes/empty"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CreateReasonRequest struct {
	UserId               uint64   `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	ActionId             uint64   `protobuf:"varint,2,opt,name=actionId,proto3" json:"actionId,omitempty"`
	Why                  string   `protobuf:"bytes,3,opt,name=why,proto3" json:"why,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateReasonRequest) Reset()         { *m = CreateReasonRequest{} }
func (m *CreateReasonRequest) String() string { return proto.CompactTextString(m) }
func (*CreateReasonRequest) ProtoMessage()    {}
func (*CreateReasonRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7afbb03a25186fc4, []int{0}
}

func (m *CreateReasonRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateReasonRequest.Unmarshal(m, b)
}
func (m *CreateReasonRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateReasonRequest.Marshal(b, m, deterministic)
}
func (m *CreateReasonRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateReasonRequest.Merge(m, src)
}
func (m *CreateReasonRequest) XXX_Size() int {
	return xxx_messageInfo_CreateReasonRequest.Size(m)
}
func (m *CreateReasonRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateReasonRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateReasonRequest proto.InternalMessageInfo

func (m *CreateReasonRequest) GetUserId() uint64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *CreateReasonRequest) GetActionId() uint64 {
	if m != nil {
		return m.ActionId
	}
	return 0
}

func (m *CreateReasonRequest) GetWhy() string {
	if m != nil {
		return m.Why
	}
	return ""
}

type CreateReasonResponse struct {
	Id                   uint64   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateReasonResponse) Reset()         { *m = CreateReasonResponse{} }
func (m *CreateReasonResponse) String() string { return proto.CompactTextString(m) }
func (*CreateReasonResponse) ProtoMessage()    {}
func (*CreateReasonResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7afbb03a25186fc4, []int{1}
}

func (m *CreateReasonResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateReasonResponse.Unmarshal(m, b)
}
func (m *CreateReasonResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateReasonResponse.Marshal(b, m, deterministic)
}
func (m *CreateReasonResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateReasonResponse.Merge(m, src)
}
func (m *CreateReasonResponse) XXX_Size() int {
	return xxx_messageInfo_CreateReasonResponse.Size(m)
}
func (m *CreateReasonResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateReasonResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateReasonResponse proto.InternalMessageInfo

func (m *CreateReasonResponse) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type DescribeReasonRequest struct {
	Id                   uint64   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DescribeReasonRequest) Reset()         { *m = DescribeReasonRequest{} }
func (m *DescribeReasonRequest) String() string { return proto.CompactTextString(m) }
func (*DescribeReasonRequest) ProtoMessage()    {}
func (*DescribeReasonRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7afbb03a25186fc4, []int{2}
}

func (m *DescribeReasonRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DescribeReasonRequest.Unmarshal(m, b)
}
func (m *DescribeReasonRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DescribeReasonRequest.Marshal(b, m, deterministic)
}
func (m *DescribeReasonRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DescribeReasonRequest.Merge(m, src)
}
func (m *DescribeReasonRequest) XXX_Size() int {
	return xxx_messageInfo_DescribeReasonRequest.Size(m)
}
func (m *DescribeReasonRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DescribeReasonRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DescribeReasonRequest proto.InternalMessageInfo

func (m *DescribeReasonRequest) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type DescribeReasonResponse struct {
	Reason               *Reason  `protobuf:"bytes,1,opt,name=Reason,proto3" json:"Reason,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DescribeReasonResponse) Reset()         { *m = DescribeReasonResponse{} }
func (m *DescribeReasonResponse) String() string { return proto.CompactTextString(m) }
func (*DescribeReasonResponse) ProtoMessage()    {}
func (*DescribeReasonResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7afbb03a25186fc4, []int{3}
}

func (m *DescribeReasonResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DescribeReasonResponse.Unmarshal(m, b)
}
func (m *DescribeReasonResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DescribeReasonResponse.Marshal(b, m, deterministic)
}
func (m *DescribeReasonResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DescribeReasonResponse.Merge(m, src)
}
func (m *DescribeReasonResponse) XXX_Size() int {
	return xxx_messageInfo_DescribeReasonResponse.Size(m)
}
func (m *DescribeReasonResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DescribeReasonResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DescribeReasonResponse proto.InternalMessageInfo

func (m *DescribeReasonResponse) GetReason() *Reason {
	if m != nil {
		return m.Reason
	}
	return nil
}

type RemoveReasonRequest struct {
	Id                   uint64   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RemoveReasonRequest) Reset()         { *m = RemoveReasonRequest{} }
func (m *RemoveReasonRequest) String() string { return proto.CompactTextString(m) }
func (*RemoveReasonRequest) ProtoMessage()    {}
func (*RemoveReasonRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7afbb03a25186fc4, []int{4}
}

func (m *RemoveReasonRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RemoveReasonRequest.Unmarshal(m, b)
}
func (m *RemoveReasonRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RemoveReasonRequest.Marshal(b, m, deterministic)
}
func (m *RemoveReasonRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RemoveReasonRequest.Merge(m, src)
}
func (m *RemoveReasonRequest) XXX_Size() int {
	return xxx_messageInfo_RemoveReasonRequest.Size(m)
}
func (m *RemoveReasonRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RemoveReasonRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RemoveReasonRequest proto.InternalMessageInfo

func (m *RemoveReasonRequest) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type ListReasonsResponse struct {
	Items                []*Reason `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *ListReasonsResponse) Reset()         { *m = ListReasonsResponse{} }
func (m *ListReasonsResponse) String() string { return proto.CompactTextString(m) }
func (*ListReasonsResponse) ProtoMessage()    {}
func (*ListReasonsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7afbb03a25186fc4, []int{5}
}

func (m *ListReasonsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListReasonsResponse.Unmarshal(m, b)
}
func (m *ListReasonsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListReasonsResponse.Marshal(b, m, deterministic)
}
func (m *ListReasonsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListReasonsResponse.Merge(m, src)
}
func (m *ListReasonsResponse) XXX_Size() int {
	return xxx_messageInfo_ListReasonsResponse.Size(m)
}
func (m *ListReasonsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListReasonsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListReasonsResponse proto.InternalMessageInfo

func (m *ListReasonsResponse) GetItems() []*Reason {
	if m != nil {
		return m.Items
	}
	return nil
}

type Reason struct {
	Id                   uint64   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId               uint64   `protobuf:"varint,2,opt,name=userId,proto3" json:"userId,omitempty"`
	ActionId             uint64   `protobuf:"varint,3,opt,name=actionId,proto3" json:"actionId,omitempty"`
	Why                  string   `protobuf:"bytes,4,opt,name=why,proto3" json:"why,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Reason) Reset()         { *m = Reason{} }
func (m *Reason) String() string { return proto.CompactTextString(m) }
func (*Reason) ProtoMessage()    {}
func (*Reason) Descriptor() ([]byte, []int) {
	return fileDescriptor_7afbb03a25186fc4, []int{6}
}

func (m *Reason) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Reason.Unmarshal(m, b)
}
func (m *Reason) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Reason.Marshal(b, m, deterministic)
}
func (m *Reason) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Reason.Merge(m, src)
}
func (m *Reason) XXX_Size() int {
	return xxx_messageInfo_Reason.Size(m)
}
func (m *Reason) XXX_DiscardUnknown() {
	xxx_messageInfo_Reason.DiscardUnknown(m)
}

var xxx_messageInfo_Reason proto.InternalMessageInfo

func (m *Reason) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Reason) GetUserId() uint64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *Reason) GetActionId() uint64 {
	if m != nil {
		return m.ActionId
	}
	return 0
}

func (m *Reason) GetWhy() string {
	if m != nil {
		return m.Why
	}
	return ""
}

func init() {
	proto.RegisterType((*CreateReasonRequest)(nil), "ova.reason.api.CreateReasonRequest")
	proto.RegisterType((*CreateReasonResponse)(nil), "ova.reason.api.CreateReasonResponse")
	proto.RegisterType((*DescribeReasonRequest)(nil), "ova.reason.api.DescribeReasonRequest")
	proto.RegisterType((*DescribeReasonResponse)(nil), "ova.reason.api.DescribeReasonResponse")
	proto.RegisterType((*RemoveReasonRequest)(nil), "ova.reason.api.RemoveReasonRequest")
	proto.RegisterType((*ListReasonsResponse)(nil), "ova.reason.api.ListReasonsResponse")
	proto.RegisterType((*Reason)(nil), "ova.reason.api.Reason")
}

func init() { proto.RegisterFile("api/ova-reason-api.proto", fileDescriptor_7afbb03a25186fc4) }

var fileDescriptor_7afbb03a25186fc4 = []byte{
	// 391 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x93, 0x41, 0xcf, 0xd2, 0x40,
	0x10, 0x86, 0xd3, 0xf6, 0x93, 0xc8, 0x40, 0x88, 0x59, 0xb4, 0x69, 0xea, 0x85, 0x54, 0x41, 0x0e,
	0xb2, 0x4d, 0xf0, 0xe8, 0x0d, 0x30, 0x11, 0xf5, 0xd4, 0x9b, 0x9a, 0x48, 0xb6, 0x65, 0x2d, 0x1b,
	0x6d, 0x77, 0xed, 0x6e, 0x6b, 0xf0, 0xd7, 0xfa, 0x53, 0xbe, 0xd0, 0x16, 0x52, 0x96, 0x02, 0xb7,
	0xce, 0xec, 0xb3, 0xf3, 0xce, 0xbe, 0x33, 0x05, 0x87, 0x08, 0xe6, 0xf3, 0x82, 0xcc, 0x32, 0x4a,
	0x24, 0x4f, 0x67, 0x44, 0x30, 0x2c, 0x32, 0xae, 0x38, 0x1a, 0xf0, 0x82, 0xe0, 0x2a, 0x8b, 0x89,
	0x60, 0xee, 0xcb, 0x98, 0xf3, 0xf8, 0x37, 0xf5, 0xcb, 0xd3, 0x30, 0xff, 0xe9, 0xd3, 0x44, 0xa8,
	0x7d, 0x05, 0x7b, 0xdf, 0x61, 0xb8, 0xcc, 0x28, 0x51, 0x34, 0x28, 0x2f, 0x04, 0xf4, 0x4f, 0x4e,
	0xa5, 0x42, 0x36, 0x74, 0x72, 0x49, 0xb3, 0xf5, 0xd6, 0x31, 0x46, 0xc6, 0xf4, 0x21, 0xa8, 0x23,
	0xe4, 0xc2, 0x53, 0x12, 0x29, 0xc6, 0xd3, 0xf5, 0xd6, 0x31, 0xcb, 0x93, 0x53, 0x8c, 0x9e, 0x81,
	0xf5, 0x77, 0xb7, 0x77, 0xac, 0x91, 0x31, 0xed, 0x06, 0x87, 0x4f, 0x6f, 0x02, 0xcf, 0xcf, 0x8b,
	0x4b, 0xc1, 0x53, 0x49, 0xd1, 0x00, 0x4c, 0x76, 0xac, 0x6c, 0xb2, 0xad, 0xf7, 0x06, 0x5e, 0xac,
	0xa8, 0x8c, 0x32, 0x16, 0x6a, 0x6d, 0xe8, 0xe0, 0x47, 0xb0, 0x75, 0xb0, 0x2e, 0x89, 0xa1, 0x53,
	0x65, 0x4a, 0xba, 0x37, 0xb7, 0xf1, 0xb9, 0x0b, 0xb8, 0xe6, 0x6b, 0xca, 0x1b, 0xc3, 0x30, 0xa0,
	0x09, 0x2f, 0xee, 0x08, 0x2e, 0x61, 0xf8, 0x85, 0x49, 0x55, 0x41, 0xf2, 0xa4, 0xf6, 0x16, 0x9e,
	0x30, 0x45, 0x13, 0xe9, 0x18, 0x23, 0xeb, 0x86, 0x58, 0x05, 0x79, 0x3f, 0x8e, 0xbd, 0xe9, 0xe5,
	0x1b, 0x36, 0x9b, 0x57, 0x6d, 0xb6, 0xda, 0x6d, 0x7e, 0x38, 0xd9, 0x3c, 0xff, 0x6f, 0x42, 0xb7,
	0x56, 0x14, 0x11, 0xfa, 0x0a, 0xfd, 0xa6, 0xe9, 0xe8, 0x95, 0xde, 0x5c, 0xcb, 0xbc, 0xdd, 0xd7,
	0xb7, 0xa1, 0xfa, 0xd9, 0x1b, 0x18, 0x9c, 0xdb, 0x8f, 0xc6, 0xfa, 0xbd, 0xd6, 0x39, 0xba, 0x93,
	0x7b, 0x58, 0x2d, 0xf0, 0x09, 0x7a, 0x0d, 0xbb, 0x91, 0x8d, 0xab, 0xd5, 0xc5, 0xc7, 0xd5, 0xc5,
	0x1f, 0x0e, 0xab, 0xeb, 0x5e, 0x3c, 0xa9, 0x6d, 0x46, 0x9f, 0xa1, 0xdf, 0x9c, 0xf0, 0xa5, 0x0f,
	0x2d, 0xf3, 0x77, 0xaf, 0x28, 0x2e, 0x56, 0xdf, 0x16, 0x31, 0x53, 0xbb, 0x3c, 0xc4, 0x11, 0x4f,
	0x7c, 0xfe, 0x8f, 0xa7, 0x05, 0xd1, 0xfe, 0x3e, 0x5f, 0xfc, 0x8a, 0xb5, 0xd4, 0x7b, 0x5e, 0x90,
	0x4d, 0x15, 0x6e, 0x88, 0x60, 0x61, 0xa7, 0xac, 0xfa, 0xee, 0x31, 0x00, 0x00, 0xff, 0xff, 0x4e,
	0xb4, 0x09, 0x15, 0xbc, 0x03, 0x00, 0x00,
}
